# Generated by Django 6.0.6 on 2026-07-05 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(db_index=True, max_length=16, unique=True)),
                ('phase', models.CharField(default='preflop', max_length=16)),
                ('pot', models.IntegerField(default=0)),
                ('current_bet', models.IntegerField(default=0)),
                ('last_raise', models.IntegerField(default=20)),
                ('small_blind', models.IntegerField(default=10)),
                ('big_blind', models.IntegerField(default=20)),
                ('raises_this_round', models.IntegerField(default=0)),
                ('dealer_orbit_count', models.IntegerField(default=-1)),
                ('game_started', models.BooleanField(default=False)),
                ('game_finished', models.BooleanField(default=False)),
                ('open_cards_mode', models.BooleanField(default=False)),
                ('spectator_mode', models.BooleanField(default=False)),
                ('initial_dealer_name', models.CharField(blank=True, max_length=64, null=True)),
                ('deck', models.TextField(default='[]')),
                ('card_graveyard', models.TextField(default='[]')),
                ('community_cards', models.TextField(default='[]')),
                ('current_player_index', models.IntegerField(default=0)),
                ('total_hands', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0)),
                ('notifications', models.TextField(default='[]')),
            ],
            options={
                'db_table': 'poker_game',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('seat_index', models.IntegerField()),
                ('is_bot', models.BooleanField(default=False)),
                ('chips', models.IntegerField(default=2000)),
                ('round_bet', models.IntegerField(default=0)),
                ('total_bet', models.IntegerField(default=0)),
                ('folded', models.BooleanField(default=False)),
                ('all_in', models.BooleanField(default=False)),
                ('is_dealer', models.BooleanField(default=False)),
                ('is_small_blind', models.BooleanField(default=False)),
                ('is_big_blind', models.BooleanField(default=False)),
                ('card1', models.CharField(blank=True, max_length=4, null=True)),
                ('card2', models.CharField(blank=True, max_length=4, null=True)),
                ('win_probability', models.FloatField(blank=True, null=True)),
                ('stats_data', models.TextField(default='{}')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='poker.game')),
            ],
            options={
                'db_table': 'poker_player',
                'unique_together': {('game', 'seat_index')},
            },
        ),
    ]
