// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deposits.sql

package repository

import (
	"context"
	"database/sql"
)

const countBankDepositsByStatus = `-- name: CountBankDepositsByStatus :one
SELECT COUNT(*) FROM bank_deposits WHERE status = $1
`

func (q *Queries) CountBankDepositsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBankDepositsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBankDeposit = `-- name: CreateBankDeposit :one
INSERT INTO bank_deposits (
    user_id, provider, receipt_url, reference, amount,
    payer_name, payer_account, status, note, transaction_id, resolved_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type CreateBankDepositParams struct {
	UserID        int64
	Provider      string
	ReceiptUrl    string
	Reference     sql.NullString
	Amount        int64
	PayerName     string
	PayerAccount  string
	Status        string
	Note          string
	TransactionID sql.NullString
	ResolvedAt    int64
}

func (q *Queries) CreateBankDeposit(ctx context.Context, arg CreateBankDepositParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createBankDeposit,
		arg.UserID,
		arg.Provider,
		arg.ReceiptUrl,
		arg.Reference,
		arg.Amount,
		arg.PayerName,
		arg.PayerAccount,
		arg.Status,
		arg.Note,
		arg.TransactionID,
		arg.ResolvedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteBankDeposit = `-- name: DeleteBankDeposit :exec
DELETE FROM bank_deposits WHERE id = $1
`

func (q *Queries) DeleteBankDeposit(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBankDeposit, id)
	return err
}

const getBankDepositByID = `-- name: GetBankDepositByID :one
SELECT id, user_id, provider, receipt_url, reference, amount, payer_name, payer_account, status, note, transaction_id, attempts, last_attempt_at, created_at, resolved_at FROM bank_deposits WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBankDepositByID(ctx context.Context, id int64) (BankDeposit, error) {
	row := q.db.QueryRowContext(ctx, getBankDepositByID, id)
	var i BankDeposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ReceiptUrl,
		&i.Reference,
		&i.Amount,
		&i.PayerName,
		&i.PayerAccount,
		&i.Status,
		&i.Note,
		&i.TransactionID,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getBankDepositByReference = `-- name: GetBankDepositByReference :one
SELECT id, user_id, provider, receipt_url, reference, amount, payer_name, payer_account, status, note, transaction_id, attempts, last_attempt_at, created_at, resolved_at FROM bank_deposits WHERE reference = $1 LIMIT 1
`

func (q *Queries) GetBankDepositByReference(ctx context.Context, reference sql.NullString) (BankDeposit, error) {
	row := q.db.QueryRowContext(ctx, getBankDepositByReference, reference)
	var i BankDeposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ReceiptUrl,
		&i.Reference,
		&i.Amount,
		&i.PayerName,
		&i.PayerAccount,
		&i.Status,
		&i.Note,
		&i.TransactionID,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getBankDepositByURL = `-- name: GetBankDepositByURL :one
SELECT id, user_id, provider, receipt_url, reference, amount, payer_name, payer_account, status, note, transaction_id, attempts, last_attempt_at, created_at, resolved_at FROM bank_deposits WHERE receipt_url = $1 LIMIT 1
`

func (q *Queries) GetBankDepositByURL(ctx context.Context, receiptUrl string) (BankDeposit, error) {
	row := q.db.QueryRowContext(ctx, getBankDepositByURL, receiptUrl)
	var i BankDeposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ReceiptUrl,
		&i.Reference,
		&i.Amount,
		&i.PayerName,
		&i.PayerAccount,
		&i.Status,
		&i.Note,
		&i.TransactionID,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listBankDepositsByUser = `-- name: ListBankDepositsByUser :many
SELECT id, user_id, provider, receipt_url, reference, amount, payer_name, payer_account, status, note, transaction_id, attempts, last_attempt_at, created_at, resolved_at FROM bank_deposits
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListBankDepositsByUserParams struct {
	UserID int64
	Limit  int32
}

func (q *Queries) ListBankDepositsByUser(ctx context.Context, arg ListBankDepositsByUserParams) ([]BankDeposit, error) {
	rows, err := q.db.QueryContext(ctx, listBankDepositsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankDeposit
	for rows.Next() {
		var i BankDeposit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ReceiptUrl,
			&i.Reference,
			&i.Amount,
			&i.PayerName,
			&i.PayerAccount,
			&i.Status,
			&i.Note,
			&i.TransactionID,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankDepositsForReview = `-- name: ListBankDepositsForReview :many
SELECT d.id, d.user_id, d.provider, d.receipt_url, d.reference, d.amount, d.payer_name, d.payer_account, d.status, d.note, d.transaction_id, d.attempts, d.last_attempt_at, d.created_at, d.resolved_at, u.username FROM bank_deposits d
JOIN users u ON u.id = d.user_id
WHERE d.status = $1
ORDER BY d.created_at DESC, d.id DESC
LIMIT $2 OFFSET $3
`

type ListBankDepositsForReviewParams struct {
	Status string
	Limit  int32
	Offset int32
}

type ListBankDepositsForReviewRow struct {
	BankDeposit BankDeposit
	Username    string
}

func (q *Queries) ListBankDepositsForReview(ctx context.Context, arg ListBankDepositsForReviewParams) ([]ListBankDepositsForReviewRow, error) {
	rows, err := q.db.QueryContext(ctx, listBankDepositsForReview, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBankDepositsForReviewRow
	for rows.Next() {
		var i ListBankDepositsForReviewRow
		if err := rows.Scan(
			&i.BankDeposit.ID,
			&i.BankDeposit.UserID,
			&i.BankDeposit.Provider,
			&i.BankDeposit.ReceiptUrl,
			&i.BankDeposit.Reference,
			&i.BankDeposit.Amount,
			&i.BankDeposit.PayerName,
			&i.BankDeposit.PayerAccount,
			&i.BankDeposit.Status,
			&i.BankDeposit.Note,
			&i.BankDeposit.TransactionID,
			&i.BankDeposit.Attempts,
			&i.BankDeposit.LastAttemptAt,
			&i.BankDeposit.CreatedAt,
			&i.BankDeposit.ResolvedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankDepositsToRetry = `-- name: ListBankDepositsToRetry :many
SELECT id, user_id, provider, receipt_url, reference, amount, payer_name, payer_account, status, note, transaction_id, attempts, last_attempt_at, created_at, resolved_at FROM bank_deposits
WHERE status = $1
  AND attempts < $2
  AND last_attempt_at <= $3
ORDER BY last_attempt_at ASC, id ASC
LIMIT $4
`

type ListBankDepositsToRetryParams struct {
	Status        string
	Attempts      int32
	LastAttemptAt int64
	Limit         int32
}

func (q *Queries) ListBankDepositsToRetry(ctx context.Context, arg ListBankDepositsToRetryParams) ([]BankDeposit, error) {
	rows, err := q.db.QueryContext(ctx, listBankDepositsToRetry,
		arg.Status,
		arg.Attempts,
		arg.LastAttemptAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankDeposit
	for rows.Next() {
		var i BankDeposit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ReceiptUrl,
			&i.Reference,
			&i.Amount,
			&i.PayerName,
			&i.PayerAccount,
			&i.Status,
			&i.Note,
			&i.TransactionID,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const noteBankDepositAttempt = `-- name: NoteBankDepositAttempt :exec
UPDATE bank_deposits
SET note = $1
WHERE id = $2
`

type NoteBankDepositAttemptParams struct {
	Note string
	ID   int64
}

func (q *Queries) NoteBankDepositAttempt(ctx context.Context, arg NoteBankDepositAttemptParams) error {
	_, err := q.db.ExecContext(ctx, noteBankDepositAttempt, arg.Note, arg.ID)
	return err
}

const resolveBankDeposit = `-- name: ResolveBankDeposit :exec
UPDATE bank_deposits
SET reference = $1,
    amount = $2,
    payer_name = $3,
    payer_account = $4,
    status = $5,
    note = $6,
    transaction_id = $7,
    resolved_at = $8
WHERE id = $9
`

type ResolveBankDepositParams struct {
	Reference     sql.NullString
	Amount        int64
	PayerName     string
	PayerAccount  string
	Status        string
	Note          string
	TransactionID sql.NullString
	ResolvedAt    int64
	ID            int64
}

func (q *Queries) ResolveBankDeposit(ctx context.Context, arg ResolveBankDepositParams) error {
	_, err := q.db.ExecContext(ctx, resolveBankDeposit,
		arg.Reference,
		arg.Amount,
		arg.PayerName,
		arg.PayerAccount,
		arg.Status,
		arg.Note,
		arg.TransactionID,
		arg.ResolvedAt,
		arg.ID,
	)
	return err
}

const touchBankDepositAttempt = `-- name: TouchBankDepositAttempt :exec
UPDATE bank_deposits
SET attempts = attempts + 1,
    last_attempt_at = $1,
    note = $2
WHERE id = $3
`

type TouchBankDepositAttemptParams struct {
	LastAttemptAt int64
	Note          string
	ID            int64
}

func (q *Queries) TouchBankDepositAttempt(ctx context.Context, arg TouchBankDepositAttemptParams) error {
	_, err := q.db.ExecContext(ctx, touchBankDepositAttempt, arg.LastAttemptAt, arg.Note, arg.ID)
	return err
}
