// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game.sql

package repository

import (
	"context"
	"database/sql"
)

const createGame = `-- name: CreateGame :execresult
INSERT INTO poker_game (table_id, phase, pot, current_bet, last_raise, small_blind, big_blind, raises_this_round, dealer_orbit_count, game_started, game_finished, open_cards_mode, spectator_mode, initial_dealer_name, deck, card_graveyard, community_cards, current_player_index, total_hands, version, notifications, intermission, last_winner_json, pot_awards_json, intermission_started_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateGameParams struct {
	TableID               string
	Phase                 string
	Pot                   int32
	CurrentBet            int32
	LastRaise             int32
	SmallBlind            int32
	BigBlind              int32
	RaisesThisRound       int32
	DealerOrbitCount      int32
	GameStarted           bool
	GameFinished          bool
	OpenCardsMode         bool
	SpectatorMode         bool
	InitialDealerName     sql.NullString
	Deck                  string
	CardGraveyard         string
	CommunityCards        string
	CurrentPlayerIndex    int32
	TotalHands            int32
	Version               int32
	Notifications         string
	Intermission          bool
	LastWinnerJson        string
	PotAwardsJson         string
	IntermissionStartedAt int64
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createGame,
		arg.TableID,
		arg.Phase,
		arg.Pot,
		arg.CurrentBet,
		arg.LastRaise,
		arg.SmallBlind,
		arg.BigBlind,
		arg.RaisesThisRound,
		arg.DealerOrbitCount,
		arg.GameStarted,
		arg.GameFinished,
		arg.OpenCardsMode,
		arg.SpectatorMode,
		arg.InitialDealerName,
		arg.Deck,
		arg.CardGraveyard,
		arg.CommunityCards,
		arg.CurrentPlayerIndex,
		arg.TotalHands,
		arg.Version,
		arg.Notifications,
		arg.Intermission,
		arg.LastWinnerJson,
		arg.PotAwardsJson,
		arg.IntermissionStartedAt,
	)
}

const createPlayer = `-- name: CreatePlayer :execresult
INSERT INTO poker_player (game_id, user_id, name, seat_index, is_bot, chips, round_bet, total_bet, folded, all_in, is_dealer, is_small_blind, is_big_blind, card1, card2, win_probability, stats_data)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePlayerParams struct {
	GameID         int64
	UserID         sql.NullInt64
	Name           string
	SeatIndex      int32
	IsBot          bool
	Chips          int32
	RoundBet       int32
	TotalBet       int32
	Folded         bool
	AllIn          bool
	IsDealer       bool
	IsSmallBlind   bool
	IsBigBlind     bool
	Card1          sql.NullString
	Card2          sql.NullString
	WinProbability sql.NullFloat64
	StatsData      string
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPlayer,
		arg.GameID,
		arg.UserID,
		arg.Name,
		arg.SeatIndex,
		arg.IsBot,
		arg.Chips,
		arg.RoundBet,
		arg.TotalBet,
		arg.Folded,
		arg.AllIn,
		arg.IsDealer,
		arg.IsSmallBlind,
		arg.IsBigBlind,
		arg.Card1,
		arg.Card2,
		arg.WinProbability,
		arg.StatsData,
	)
}

const deletePlayersByGameID = `-- name: DeletePlayersByGameID :exec
DELETE FROM poker_player WHERE game_id = ?
`

func (q *Queries) DeletePlayersByGameID(ctx context.Context, gameID int64) error {
	_, err := q.db.ExecContext(ctx, deletePlayersByGameID, gameID)
	return err
}

const getGameByTableID = `-- name: GetGameByTableID :one
SELECT id, table_id, phase, pot, current_bet, last_raise, small_blind, big_blind, raises_this_round, dealer_orbit_count, game_started, game_finished, open_cards_mode, spectator_mode, initial_dealer_name, deck, card_graveyard, community_cards, current_player_index, total_hands, created_at, updated_at, version, notifications, intermission, last_winner_json, pot_awards_json, intermission_started_at
FROM poker_game
WHERE table_id = ? LIMIT 1
`

func (q *Queries) GetGameByTableID(ctx context.Context, tableID string) (PokerGame, error) {
	row := q.db.QueryRowContext(ctx, getGameByTableID, tableID)
	var i PokerGame
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.Phase,
		&i.Pot,
		&i.CurrentBet,
		&i.LastRaise,
		&i.SmallBlind,
		&i.BigBlind,
		&i.RaisesThisRound,
		&i.DealerOrbitCount,
		&i.GameStarted,
		&i.GameFinished,
		&i.OpenCardsMode,
		&i.SpectatorMode,
		&i.InitialDealerName,
		&i.Deck,
		&i.CardGraveyard,
		&i.CommunityCards,
		&i.CurrentPlayerIndex,
		&i.TotalHands,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.Notifications,
		&i.Intermission,
		&i.LastWinnerJson,
		&i.PotAwardsJson,
		&i.IntermissionStartedAt,
	)
	return i, err
}

const getPlayersByGameID = `-- name: GetPlayersByGameID :many
SELECT id, game_id, user_id, name, seat_index, is_bot, chips, round_bet, total_bet, folded, all_in, is_dealer, is_small_blind, is_big_blind, card1, card2, win_probability, stats_data
FROM poker_player
WHERE game_id = ?
ORDER BY seat_index ASC
`

func (q *Queries) GetPlayersByGameID(ctx context.Context, gameID int64) ([]PokerPlayer, error) {
	rows, err := q.db.QueryContext(ctx, getPlayersByGameID, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PokerPlayer
	for rows.Next() {
		var i PokerPlayer
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.Name,
			&i.SeatIndex,
			&i.IsBot,
			&i.Chips,
			&i.RoundBet,
			&i.TotalBet,
			&i.Folded,
			&i.AllIn,
			&i.IsDealer,
			&i.IsSmallBlind,
			&i.IsBigBlind,
			&i.Card1,
			&i.Card2,
			&i.WinProbability,
			&i.StatsData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGame = `-- name: UpdateGame :exec
UPDATE poker_game
SET phase = ?, pot = ?, current_bet = ?, last_raise = ?, small_blind = ?, big_blind = ?, raises_this_round = ?, dealer_orbit_count = ?, game_started = ?, game_finished = ?, open_cards_mode = ?, spectator_mode = ?, initial_dealer_name = ?, deck = ?, card_graveyard = ?, community_cards = ?, current_player_index = ?, total_hands = ?, version = version + 1, notifications = ?, intermission = ?, last_winner_json = ?, pot_awards_json = ?, intermission_started_at = ?
WHERE id = ? AND version = ?
`

type UpdateGameParams struct {
	Phase                 string
	Pot                   int32
	CurrentBet            int32
	LastRaise             int32
	SmallBlind            int32
	BigBlind              int32
	RaisesThisRound       int32
	DealerOrbitCount      int32
	GameStarted           bool
	GameFinished          bool
	OpenCardsMode         bool
	SpectatorMode         bool
	InitialDealerName     sql.NullString
	Deck                  string
	CardGraveyard         string
	CommunityCards        string
	CurrentPlayerIndex    int32
	TotalHands            int32
	Notifications         string
	Intermission          bool
	LastWinnerJson        string
	PotAwardsJson         string
	IntermissionStartedAt int64
	ID                    int64
	Version               int32
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) error {
	_, err := q.db.ExecContext(ctx, updateGame,
		arg.Phase,
		arg.Pot,
		arg.CurrentBet,
		arg.LastRaise,
		arg.SmallBlind,
		arg.BigBlind,
		arg.RaisesThisRound,
		arg.DealerOrbitCount,
		arg.GameStarted,
		arg.GameFinished,
		arg.OpenCardsMode,
		arg.SpectatorMode,
		arg.InitialDealerName,
		arg.Deck,
		arg.CardGraveyard,
		arg.CommunityCards,
		arg.CurrentPlayerIndex,
		arg.TotalHands,
		arg.Notifications,
		arg.Intermission,
		arg.LastWinnerJson,
		arg.PotAwardsJson,
		arg.IntermissionStartedAt,
		arg.ID,
		arg.Version,
	)
	return err
}
