// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gateway_deposits.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const attachGatewayCheckout = `-- name: AttachGatewayCheckout :exec
UPDATE gateway_deposits
SET router_payment_id = $1,
    checkout_url = $2
WHERE id = $3
`

type AttachGatewayCheckoutParams struct {
	RouterPaymentID string
	CheckoutUrl     string
	ID              int64
}

func (q *Queries) AttachGatewayCheckout(ctx context.Context, arg AttachGatewayCheckoutParams) error {
	_, err := q.db.ExecContext(ctx, attachGatewayCheckout, arg.RouterPaymentID, arg.CheckoutUrl, arg.ID)
	return err
}

const createGatewayDeposit = `-- name: CreateGatewayDeposit :one
INSERT INTO gateway_deposits (user_id, reference, amount, status)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateGatewayDepositParams struct {
	UserID    int64
	Reference string
	Amount    int64
	Status    string
}

func (q *Queries) CreateGatewayDeposit(ctx context.Context, arg CreateGatewayDepositParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createGatewayDeposit,
		arg.UserID,
		arg.Reference,
		arg.Amount,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getGatewayDepositByReference = `-- name: GetGatewayDepositByReference :one
SELECT id, user_id, reference, router_payment_id, amount, status, checkout_url, transaction_id, last_event, note, created_at, resolved_at FROM gateway_deposits WHERE reference = $1 LIMIT 1
`

func (q *Queries) GetGatewayDepositByReference(ctx context.Context, reference string) (GatewayDeposit, error) {
	row := q.db.QueryRowContext(ctx, getGatewayDepositByReference, reference)
	var i GatewayDeposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Reference,
		&i.RouterPaymentID,
		&i.Amount,
		&i.Status,
		&i.CheckoutUrl,
		&i.TransactionID,
		&i.LastEvent,
		&i.Note,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getGatewayDepositForUpdate = `-- name: GetGatewayDepositForUpdate :one
SELECT id, user_id, reference, router_payment_id, amount, status, checkout_url, transaction_id, last_event, note, created_at, resolved_at FROM gateway_deposits WHERE reference = $1 FOR UPDATE
`

func (q *Queries) GetGatewayDepositForUpdate(ctx context.Context, reference string) (GatewayDeposit, error) {
	row := q.db.QueryRowContext(ctx, getGatewayDepositForUpdate, reference)
	var i GatewayDeposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Reference,
		&i.RouterPaymentID,
		&i.Amount,
		&i.Status,
		&i.CheckoutUrl,
		&i.TransactionID,
		&i.LastEvent,
		&i.Note,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listGatewayDepositsByUser = `-- name: ListGatewayDepositsByUser :many
SELECT id, user_id, reference, router_payment_id, amount, status, checkout_url, transaction_id, last_event, note, created_at, resolved_at FROM gateway_deposits
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListGatewayDepositsByUserParams struct {
	UserID int64
	Limit  int32
}

func (q *Queries) ListGatewayDepositsByUser(ctx context.Context, arg ListGatewayDepositsByUserParams) ([]GatewayDeposit, error) {
	rows, err := q.db.QueryContext(ctx, listGatewayDepositsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayDeposit
	for rows.Next() {
		var i GatewayDeposit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Reference,
			&i.RouterPaymentID,
			&i.Amount,
			&i.Status,
			&i.CheckoutUrl,
			&i.TransactionID,
			&i.LastEvent,
			&i.Note,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewayDepositsPendingSince = `-- name: ListGatewayDepositsPendingSince :many
SELECT id, user_id, reference, router_payment_id, amount, status, checkout_url, transaction_id, last_event, note, created_at, resolved_at FROM gateway_deposits
WHERE status = $1
  AND router_payment_id <> ''
  AND created_at <= $2
ORDER BY created_at ASC, id ASC
LIMIT $3
`

type ListGatewayDepositsPendingSinceParams struct {
	Status    string
	CreatedAt time.Time
	Limit     int32
}

func (q *Queries) ListGatewayDepositsPendingSince(ctx context.Context, arg ListGatewayDepositsPendingSinceParams) ([]GatewayDeposit, error) {
	rows, err := q.db.QueryContext(ctx, listGatewayDepositsPendingSince, arg.Status, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayDeposit
	for rows.Next() {
		var i GatewayDeposit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Reference,
			&i.RouterPaymentID,
			&i.Amount,
			&i.Status,
			&i.CheckoutUrl,
			&i.TransactionID,
			&i.LastEvent,
			&i.Note,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveGatewayDeposit = `-- name: ResolveGatewayDeposit :exec
UPDATE gateway_deposits
SET status = $1,
    transaction_id = $2,
    last_event = $3,
    note = $4,
    resolved_at = $5
WHERE id = $6
`

type ResolveGatewayDepositParams struct {
	Status        string
	TransactionID sql.NullString
	LastEvent     string
	Note          string
	ResolvedAt    int64
	ID            int64
}

func (q *Queries) ResolveGatewayDeposit(ctx context.Context, arg ResolveGatewayDepositParams) error {
	_, err := q.db.ExecContext(ctx, resolveGatewayDeposit,
		arg.Status,
		arg.TransactionID,
		arg.LastEvent,
		arg.Note,
		arg.ResolvedAt,
		arg.ID,
	)
	return err
}
