// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"
)

type GameSession struct {
	ID               int64
	TableID          string
	HandNumber       int32
	PotAmount        int64
	CommissionAmount int64
	WinnerUserID     sql.NullInt64
	WinnerName       string
	HandName         string
	DetailsJson      string
	CreatedAt        time.Time
}

type PokerGame struct {
	ID                    int64
	TableID               string
	Phase                 string
	Pot                   int32
	CurrentBet            int32
	LastRaise             int32
	SmallBlind            int32
	BigBlind              int32
	RaisesThisRound       int32
	DealerOrbitCount      int32
	GameStarted           bool
	GameFinished          bool
	OpenCardsMode         bool
	SpectatorMode         bool
	InitialDealerName     sql.NullString
	Deck                  string
	CardGraveyard         string
	CommunityCards        string
	CurrentPlayerIndex    int32
	TotalHands            int32
	CreatedAt             time.Time
	UpdatedAt             time.Time
	Version               int32
	Notifications         string
	Intermission          bool
	LastWinnerJson        string
	PotAwardsJson         string
	IntermissionStartedAt int64
}

type PokerPlayer struct {
	ID             int64
	GameID         int64
	UserID         sql.NullInt64
	Name           string
	SeatIndex      int32
	IsBot          bool
	Chips          int32
	RoundBet       int32
	TotalBet       int32
	Folded         bool
	AllIn          bool
	IsDealer       bool
	IsSmallBlind   bool
	IsBigBlind     bool
	Card1          sql.NullString
	Card2          sql.NullString
	WinProbability sql.NullFloat64
	StatsData      string
}

type PokerRoom struct {
	ID         int64
	RoomCode   string
	RoomName   string
	RoomType   string
	HostUserID sql.NullInt64
	BuyIn      int64
	SmallBlind int32
	BigBlind   int32
	MaxPlayers int32
	Status     string
	CreatedAt  time.Time
}

type SiteSetting struct {
	ID                        int32
	RakeMode                  string
	RakePercentage            float64
	ReferralPercentagePctMode float64
	ReferralPercentageSbMode  float64
	CountdownSeconds          int32
	UpdatedAt                 time.Time
}

type Transaction struct {
	ID            int64
	UserID        int64
	Amount        int64
	Type          string
	Reason        string
	TransactionID string
	CreatedAt     time.Time
}

type User struct {
	ID           int64
	Username     string
	PhoneNumber  string
	PasswordHash string
	Wallet       int64
	ReferralCode string
	ReferredBy   sql.NullString
	Role         string
	CreatedAt    time.Time
}

type UserSession struct {
	SessionToken string
	UserID       int64
	ExpiresAt    time.Time
	CreatedAt    time.Time
}
