// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"
)

type GameSession struct {
	ID               int64
	TableID          string
	HandNumber       int32
	PotAmount        string
	CommissionAmount string
	WinnerUserID     sql.NullInt64
	WinnerName       string
	HandName         string
	DetailsJson      string
	CreatedAt        time.Time
}

type PokerGame struct {
	ID                    int64
	TableID               string
	Phase                 string
	Pot                   int32
	CurrentBet            int32
	LastRaise             int32
	SmallBlind            int32
	BigBlind              int32
	RaisesThisRound       int32
	DealerOrbitCount      int32
	GameStarted           bool
	GameFinished          bool
	OpenCardsMode         bool
	SpectatorMode         bool
	InitialDealerName     sql.NullString
	Deck                  string
	CardGraveyard         string
	CommunityCards        string
	CurrentPlayerIndex    int32
	TotalHands            int32
	CreatedAt             time.Time
	UpdatedAt             time.Time
	Version               int32
	Notifications         string
	Intermission          bool
	LastWinnerJson        string
	PotAwardsJson         string
	IntermissionStartedAt int64
}

type PokerPlayer struct {
	ID             int64
	GameID         int64
	UserID         sql.NullInt64
	Name           string
	SeatIndex      int32
	IsBot          bool
	Chips          int32
	RoundBet       int32
	TotalBet       int32
	Folded         bool
	AllIn          bool
	IsDealer       bool
	IsSmallBlind   bool
	IsBigBlind     bool
	Card1          sql.NullString
	Card2          sql.NullString
	WinProbability sql.NullFloat64
	StatsData      string
}

type Transaction struct {
	ID            int64
	UserID        int64
	Amount        string
	Reason        string
	TransactionID string
	CreatedAt     time.Time
}

type User struct {
	ID           int64
	Username     string
	PhoneNumber  string
	PasswordHash string
	Wallet       string
	ReferralCode string
	ReferredBy   sql.NullString
	CreatedAt    time.Time
}

type UserSession struct {
	SessionToken string
	UserID       int64
	ExpiresAt    time.Time
	CreatedAt    time.Time
}
