// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otp.sql

package repository

import (
	"context"
	"database/sql"
)

const createOTPThrottle = `-- name: CreateOTPThrottle :exec
INSERT INTO otp_send_throttle (phone_number, purpose, window_started_at, last_sent_at, send_count)
VALUES ($1, $2, $3, $4, 1)
`

type CreateOTPThrottleParams struct {
	PhoneNumber     string
	Purpose         string
	WindowStartedAt int64
	LastSentAt      int64
}

func (q *Queries) CreateOTPThrottle(ctx context.Context, arg CreateOTPThrottleParams) error {
	_, err := q.db.ExecContext(ctx, createOTPThrottle,
		arg.PhoneNumber,
		arg.Purpose,
		arg.WindowStartedAt,
		arg.LastSentAt,
	)
	return err
}

const createPasswordResetCode = `-- name: CreatePasswordResetCode :exec
INSERT INTO password_reset_codes (user_id, phone_number, code, attempts, expires_at, reset_token, token_expires_at)
VALUES ($1, $2, $3, 0, $4, NULL, 0)
`

type CreatePasswordResetCodeParams struct {
	UserID      int64
	PhoneNumber string
	Code        string
	ExpiresAt   int64
}

func (q *Queries) CreatePasswordResetCode(ctx context.Context, arg CreatePasswordResetCodeParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordResetCode,
		arg.UserID,
		arg.PhoneNumber,
		arg.Code,
		arg.ExpiresAt,
	)
	return err
}

const createPendingRegistration = `-- name: CreatePendingRegistration :exec
INSERT INTO pending_registrations (username, phone_number, password_hash, referred_by, code, attempts, expires_at)
VALUES ($1, $2, $3, $4, $5, 0, $6)
`

type CreatePendingRegistrationParams struct {
	Username     string
	PhoneNumber  string
	PasswordHash string
	ReferredBy   sql.NullString
	Code         string
	ExpiresAt    int64
}

func (q *Queries) CreatePendingRegistration(ctx context.Context, arg CreatePendingRegistrationParams) error {
	_, err := q.db.ExecContext(ctx, createPendingRegistration,
		arg.Username,
		arg.PhoneNumber,
		arg.PasswordHash,
		arg.ReferredBy,
		arg.Code,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredPasswordResetCodes = `-- name: DeleteExpiredPasswordResetCodes :exec

DELETE FROM password_reset_codes WHERE expires_at < $1 AND token_expires_at < $2
`

type DeleteExpiredPasswordResetCodesParams struct {
	ExpiresAt      int64
	TokenExpiresAt int64
}

// Password reset codes -------------------------------------------------------
// A row survives until both of its clocks are dead: the code may be spent while
// the token it minted is still live.
func (q *Queries) DeleteExpiredPasswordResetCodes(ctx context.Context, arg DeleteExpiredPasswordResetCodesParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPasswordResetCodes, arg.ExpiresAt, arg.TokenExpiresAt)
	return err
}

const deleteExpiredPendingRegistrations = `-- name: DeleteExpiredPendingRegistrations :exec

DELETE FROM pending_registrations WHERE expires_at < $1
`

// Pending registrations ------------------------------------------------------
// Run at the top of every send path. This is not housekeeping: an expired row
// still holds its UNIQUE claim on a username, so deleting it is a precondition
// of the insert that follows, not a background chore.
func (q *Queries) DeleteExpiredPendingRegistrations(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPendingRegistrations, expiresAt)
	return err
}

const deletePasswordResetCodeByID = `-- name: DeletePasswordResetCodeByID :exec
DELETE FROM password_reset_codes WHERE id = $1
`

func (q *Queries) DeletePasswordResetCodeByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePasswordResetCodeByID, id)
	return err
}

const deletePasswordResetCodeByPhone = `-- name: DeletePasswordResetCodeByPhone :exec
DELETE FROM password_reset_codes WHERE phone_number = $1
`

func (q *Queries) DeletePasswordResetCodeByPhone(ctx context.Context, phoneNumber string) error {
	_, err := q.db.ExecContext(ctx, deletePasswordResetCodeByPhone, phoneNumber)
	return err
}

const deletePendingRegistrationByID = `-- name: DeletePendingRegistrationByID :exec
DELETE FROM pending_registrations WHERE id = $1
`

func (q *Queries) DeletePendingRegistrationByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePendingRegistrationByID, id)
	return err
}

const deletePendingRegistrationByPhone = `-- name: DeletePendingRegistrationByPhone :exec
DELETE FROM pending_registrations WHERE phone_number = $1
`

func (q *Queries) DeletePendingRegistrationByPhone(ctx context.Context, phoneNumber string) error {
	_, err := q.db.ExecContext(ctx, deletePendingRegistrationByPhone, phoneNumber)
	return err
}

const deleteStaleOTPThrottles = `-- name: DeleteStaleOTPThrottles :exec
DELETE FROM otp_send_throttle WHERE window_started_at < $1
`

func (q *Queries) DeleteStaleOTPThrottles(ctx context.Context, windowStartedAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteStaleOTPThrottles, windowStartedAt)
	return err
}

const getOTPThrottle = `-- name: GetOTPThrottle :one

SELECT id, phone_number, purpose, window_started_at, last_sent_at, send_count
FROM otp_send_throttle
WHERE phone_number = $1 AND purpose = $2 LIMIT 1
`

type GetOTPThrottleParams struct {
	PhoneNumber string
	Purpose     string
}

// OTP send throttle ----------------------------------------------------------
func (q *Queries) GetOTPThrottle(ctx context.Context, arg GetOTPThrottleParams) (OtpSendThrottle, error) {
	row := q.db.QueryRowContext(ctx, getOTPThrottle, arg.PhoneNumber, arg.Purpose)
	var i OtpSendThrottle
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Purpose,
		&i.WindowStartedAt,
		&i.LastSentAt,
		&i.SendCount,
	)
	return i, err
}

const getPasswordResetCodeByPhone = `-- name: GetPasswordResetCodeByPhone :one
SELECT id, user_id, phone_number, code, attempts, expires_at, reset_token, token_expires_at, created_at
FROM password_reset_codes
WHERE phone_number = $1 LIMIT 1
`

func (q *Queries) GetPasswordResetCodeByPhone(ctx context.Context, phoneNumber string) (PasswordResetCode, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetCodeByPhone, phoneNumber)
	var i PasswordResetCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PhoneNumber,
		&i.Code,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ResetToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordResetCodeByToken = `-- name: GetPasswordResetCodeByToken :one
SELECT id, user_id, phone_number, code, attempts, expires_at, reset_token, token_expires_at, created_at
FROM password_reset_codes
WHERE reset_token = $1 LIMIT 1
`

// The user this reset acts on comes from here, never from the request body.
func (q *Queries) GetPasswordResetCodeByToken(ctx context.Context, resetToken sql.NullString) (PasswordResetCode, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetCodeByToken, resetToken)
	var i PasswordResetCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PhoneNumber,
		&i.Code,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ResetToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingRegistrationByPhone = `-- name: GetPendingRegistrationByPhone :one
SELECT id, username, phone_number, password_hash, referred_by, code, attempts, expires_at, created_at
FROM pending_registrations
WHERE phone_number = $1 LIMIT 1
`

func (q *Queries) GetPendingRegistrationByPhone(ctx context.Context, phoneNumber string) (PendingRegistration, error) {
	row := q.db.QueryRowContext(ctx, getPendingRegistrationByPhone, phoneNumber)
	var i PendingRegistration
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.ReferredBy,
		&i.Code,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingRegistrationByUsername = `-- name: GetPendingRegistrationByUsername :one
SELECT id, username, phone_number, password_hash, referred_by, code, attempts, expires_at, created_at
FROM pending_registrations
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetPendingRegistrationByUsername(ctx context.Context, username string) (PendingRegistration, error) {
	row := q.db.QueryRowContext(ctx, getPendingRegistrationByUsername, username)
	var i PendingRegistration
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.ReferredBy,
		&i.Code,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementPasswordResetAttempts = `-- name: IncrementPasswordResetAttempts :exec
UPDATE password_reset_codes SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementPasswordResetAttempts(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementPasswordResetAttempts, id)
	return err
}

const incrementPendingRegistrationAttempts = `-- name: IncrementPendingRegistrationAttempts :exec
UPDATE pending_registrations SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementPendingRegistrationAttempts(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementPendingRegistrationAttempts, id)
	return err
}

const refreshPasswordResetCode = `-- name: RefreshPasswordResetCode :exec
UPDATE password_reset_codes SET code = $1, expires_at = $2, attempts = 0, reset_token = NULL, token_expires_at = 0 WHERE id = $3
`

type RefreshPasswordResetCodeParams struct {
	Code      string
	ExpiresAt int64
	ID        int64
}

func (q *Queries) RefreshPasswordResetCode(ctx context.Context, arg RefreshPasswordResetCodeParams) error {
	_, err := q.db.ExecContext(ctx, refreshPasswordResetCode, arg.Code, arg.ExpiresAt, arg.ID)
	return err
}

const refreshPendingRegistrationCode = `-- name: RefreshPendingRegistrationCode :exec
UPDATE pending_registrations SET code = $1, expires_at = $2, attempts = 0 WHERE id = $3
`

type RefreshPendingRegistrationCodeParams struct {
	Code      string
	ExpiresAt int64
	ID        int64
}

// Resend mints a new code and clears the attempt counter, so the most recent
// SMS is always the one that works and a fresh code earns a fresh five tries.
func (q *Queries) RefreshPendingRegistrationCode(ctx context.Context, arg RefreshPendingRegistrationCodeParams) error {
	_, err := q.db.ExecContext(ctx, refreshPendingRegistrationCode, arg.Code, arg.ExpiresAt, arg.ID)
	return err
}

const setPasswordResetToken = `-- name: SetPasswordResetToken :exec
UPDATE password_reset_codes SET reset_token = $1, token_expires_at = $2, code = '', expires_at = 0 WHERE id = $3
`

type SetPasswordResetTokenParams struct {
	ResetToken     sql.NullString
	TokenExpiresAt int64
	ID             int64
}

// Verifying the code burns it (code is blanked) and mints the token in one write.
func (q *Queries) SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, setPasswordResetToken, arg.ResetToken, arg.TokenExpiresAt, arg.ID)
	return err
}

const updateOTPThrottle = `-- name: UpdateOTPThrottle :exec
UPDATE otp_send_throttle SET window_started_at = $1, last_sent_at = $2, send_count = $3 WHERE id = $4
`

type UpdateOTPThrottleParams struct {
	WindowStartedAt int64
	LastSentAt      int64
	SendCount       int32
	ID              int64
}

func (q *Queries) UpdateOTPThrottle(ctx context.Context, arg UpdateOTPThrottleParams) error {
	_, err := q.db.ExecContext(ctx, updateOTPThrottle,
		arg.WindowStartedAt,
		arg.LastSentAt,
		arg.SendCount,
		arg.ID,
	)
	return err
}
