// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package repository

import (
	"context"
	"database/sql"
)

const createRoom = `-- name: CreateRoom :execresult
INSERT INTO poker_rooms (room_code, room_name, room_type, host_user_id, buy_in, small_blind, big_blind, max_players, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRoomParams struct {
	RoomCode   string
	RoomName   string
	RoomType   string
	HostUserID sql.NullInt64
	BuyIn      int64
	SmallBlind int32
	BigBlind   int32
	MaxPlayers int32
	Status     string
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRoom,
		arg.RoomCode,
		arg.RoomName,
		arg.RoomType,
		arg.HostUserID,
		arg.BuyIn,
		arg.SmallBlind,
		arg.BigBlind,
		arg.MaxPlayers,
		arg.Status,
	)
}

const getRoomByCode = `-- name: GetRoomByCode :one
SELECT id, room_code, room_name, room_type, host_user_id, buy_in, small_blind, big_blind, max_players, status, created_at
FROM poker_rooms
WHERE room_code = ? LIMIT 1
`

func (q *Queries) GetRoomByCode(ctx context.Context, roomCode string) (PokerRoom, error) {
	row := q.db.QueryRowContext(ctx, getRoomByCode, roomCode)
	var i PokerRoom
	err := row.Scan(
		&i.ID,
		&i.RoomCode,
		&i.RoomName,
		&i.RoomType,
		&i.HostUserID,
		&i.BuyIn,
		&i.SmallBlind,
		&i.BigBlind,
		&i.MaxPlayers,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listActivePublicRooms = `-- name: ListActivePublicRooms :many
SELECT id, room_code, room_name, room_type, host_user_id, buy_in, small_blind, big_blind, max_players, status, created_at
FROM poker_rooms
WHERE room_type = 'public' AND status = 'active'
ORDER BY small_blind ASC, id DESC LIMIT 60
`

// Ordered by stake first so a busy site can never starve a whole blind level
// out of the lobby: a flat "newest 20" would hide every table in the oldest
// tier once enough rooms exist.
func (q *Queries) ListActivePublicRooms(ctx context.Context) ([]PokerRoom, error) {
	rows, err := q.db.QueryContext(ctx, listActivePublicRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PokerRoom
	for rows.Next() {
		var i PokerRoom
		if err := rows.Scan(
			&i.ID,
			&i.RoomCode,
			&i.RoomName,
			&i.RoomType,
			&i.HostUserID,
			&i.BuyIn,
			&i.SmallBlind,
			&i.BigBlind,
			&i.MaxPlayers,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoomStatus = `-- name: UpdateRoomStatus :exec
UPDATE poker_rooms
SET status = ?
WHERE room_code = ?
`

type UpdateRoomStatusParams struct {
	Status   string
	RoomCode string
}

func (q *Queries) UpdateRoomStatus(ctx context.Context, arg UpdateRoomStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRoomStatus, arg.Status, arg.RoomCode)
	return err
}
