// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const createGameSession = `-- name: CreateGameSession :execresult
INSERT INTO game_sessions (table_id, hand_number, pot_amount, commission_amount, winner_user_id, winner_name, hand_name, details_json)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateGameSessionParams struct {
	TableID          string
	HandNumber       int32
	PotAmount        int64
	CommissionAmount int64
	WinnerUserID     sql.NullInt64
	WinnerName       string
	HandName         string
	DetailsJson      string
}

func (q *Queries) CreateGameSession(ctx context.Context, arg CreateGameSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createGameSession,
		arg.TableID,
		arg.HandNumber,
		arg.PotAmount,
		arg.CommissionAmount,
		arg.WinnerUserID,
		arg.WinnerName,
		arg.HandName,
		arg.DetailsJson,
	)
}

const createSessionToken = `-- name: CreateSessionToken :exec
INSERT INTO user_sessions (session_token, user_id, expires_at)
VALUES (?, ?, ?)
`

type CreateSessionTokenParams struct {
	SessionToken string
	UserID       int64
	ExpiresAt    time.Time
}

func (q *Queries) CreateSessionToken(ctx context.Context, arg CreateSessionTokenParams) error {
	_, err := q.db.ExecContext(ctx, createSessionToken, arg.SessionToken, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteSessionToken = `-- name: DeleteSessionToken :exec
DELETE FROM user_sessions WHERE session_token = ?
`

func (q *Queries) DeleteSessionToken(ctx context.Context, sessionToken string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionToken, sessionToken)
	return err
}

const getGameSessionsByTable = `-- name: GetGameSessionsByTable :many
SELECT id, table_id, hand_number, pot_amount, commission_amount, winner_user_id, winner_name, hand_name, details_json, created_at
FROM game_sessions
WHERE table_id = ?
ORDER BY id DESC LIMIT 20
`

func (q *Queries) GetGameSessionsByTable(ctx context.Context, tableID string) ([]GameSession, error) {
	rows, err := q.db.QueryContext(ctx, getGameSessionsByTable, tableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameSession
	for rows.Next() {
		var i GameSession
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.HandNumber,
			&i.PotAmount,
			&i.CommissionAmount,
			&i.WinnerUserID,
			&i.WinnerName,
			&i.HandName,
			&i.DetailsJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBySessionToken = `-- name: GetUserBySessionToken :one
SELECT u.id, u.username, u.phone_number, u.password_hash, u.wallet, u.referral_code, u.referred_by, u.role, u.created_at
FROM user_sessions s
JOIN users u ON s.user_id = u.id
WHERE s.session_token = ? AND s.expires_at > CURRENT_TIMESTAMP LIMIT 1
`

func (q *Queries) GetUserBySessionToken(ctx context.Context, sessionToken string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySessionToken, sessionToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Wallet,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
