// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const createGameSession = `-- name: CreateGameSession :one
INSERT INTO game_sessions (table_id, hand_number, pot_amount, commission_amount, winner_user_id, winner_name, hand_name, details_json)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateGameSessionParams struct {
	TableID          string
	HandNumber       int32
	PotAmount        int64
	CommissionAmount int64
	WinnerUserID     sql.NullInt64
	WinnerName       string
	HandName         string
	DetailsJson      string
}

func (q *Queries) CreateGameSession(ctx context.Context, arg CreateGameSessionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createGameSession,
		arg.TableID,
		arg.HandNumber,
		arg.PotAmount,
		arg.CommissionAmount,
		arg.WinnerUserID,
		arg.WinnerName,
		arg.HandName,
		arg.DetailsJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSessionToken = `-- name: CreateSessionToken :exec
INSERT INTO user_sessions (session_token, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionTokenParams struct {
	SessionToken string
	UserID       int64
	ExpiresAt    time.Time
}

func (q *Queries) CreateSessionToken(ctx context.Context, arg CreateSessionTokenParams) error {
	_, err := q.db.ExecContext(ctx, createSessionToken, arg.SessionToken, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteSessionToken = `-- name: DeleteSessionToken :exec
DELETE FROM user_sessions WHERE session_token = $1
`

func (q *Queries) DeleteSessionToken(ctx context.Context, sessionToken string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionToken, sessionToken)
	return err
}

const deleteSessionTokensByUser = `-- name: DeleteSessionTokensByUser :exec
DELETE FROM user_sessions WHERE user_id = $1
`

// Used when a password is reset: every other device is signed out, so an
// attacker who already holds a session cannot survive the victim's remediation.
func (q *Queries) DeleteSessionTokensByUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSessionTokensByUser, userID)
	return err
}

const extendSessionToken = `-- name: ExtendSessionToken :exec
UPDATE user_sessions SET expires_at = $1 WHERE session_token = $2
`

type ExtendSessionTokenParams struct {
	ExpiresAt    time.Time
	SessionToken string
}

func (q *Queries) ExtendSessionToken(ctx context.Context, arg ExtendSessionTokenParams) error {
	_, err := q.db.ExecContext(ctx, extendSessionToken, arg.ExpiresAt, arg.SessionToken)
	return err
}

const getGameSessionsByTable = `-- name: GetGameSessionsByTable :many
SELECT id, table_id, hand_number, pot_amount, commission_amount, winner_user_id, winner_name, hand_name, details_json, created_at
FROM game_sessions
WHERE table_id = $1
ORDER BY id DESC LIMIT 20
`

func (q *Queries) GetGameSessionsByTable(ctx context.Context, tableID string) ([]GameSession, error) {
	rows, err := q.db.QueryContext(ctx, getGameSessionsByTable, tableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameSession
	for rows.Next() {
		var i GameSession
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.HandNumber,
			&i.PotAmount,
			&i.CommissionAmount,
			&i.WinnerUserID,
			&i.WinnerName,
			&i.HandName,
			&i.DetailsJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT u.id, u.username, u.phone_number, u.password_hash, u.wallet, u.referral_code, u.referred_by, u.role, u.created_at,
       s.expires_at AS session_expires_at,
       s.created_at AS session_created_at
FROM user_sessions s
JOIN users u ON s.user_id = u.id
WHERE s.session_token = $1 AND s.expires_at > NOW() LIMIT 1
`

type GetSessionWithUserRow struct {
	ID               int64
	Username         string
	PhoneNumber      string
	PasswordHash     string
	Wallet           int64
	ReferralCode     string
	ReferredBy       sql.NullString
	Role             string
	CreatedAt        time.Time
	SessionExpiresAt time.Time
	SessionCreatedAt time.Time
}

// Returns the signed-in user together with the session's own timestamps, so a
// single round trip can both authenticate the request and decide whether the
// session is due to be slid forward (see AuthService.GetUserByToken).
func (q *Queries) GetSessionWithUser(ctx context.Context, sessionToken string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionWithUser, sessionToken)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Wallet,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.Role,
		&i.CreatedAt,
		&i.SessionExpiresAt,
		&i.SessionCreatedAt,
	)
	return i, err
}
