// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package repository

import (
	"context"
)

const getSiteSettings = `-- name: GetSiteSettings :one
SELECT id, rake_mode, rake_percentage, referral_percentage_pct_mode, referral_percentage_sb_mode, countdown_seconds, updated_at
FROM site_settings
WHERE id = 1 LIMIT 1
`

func (q *Queries) GetSiteSettings(ctx context.Context) (SiteSetting, error) {
	row := q.db.QueryRowContext(ctx, getSiteSettings)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.RakeMode,
		&i.RakePercentage,
		&i.ReferralPercentagePctMode,
		&i.ReferralPercentageSbMode,
		&i.CountdownSeconds,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSiteSettings = `-- name: UpdateSiteSettings :exec
UPDATE site_settings
SET rake_mode = ?,
    rake_percentage = ?,
    referral_percentage_pct_mode = ?,
    referral_percentage_sb_mode = ?,
    countdown_seconds = ?
WHERE id = 1
`

type UpdateSiteSettingsParams struct {
	RakeMode                  string
	RakePercentage            float64
	ReferralPercentagePctMode float64
	ReferralPercentageSbMode  float64
	CountdownSeconds          int32
}

func (q *Queries) UpdateSiteSettings(ctx context.Context, arg UpdateSiteSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSiteSettings,
		arg.RakeMode,
		arg.RakePercentage,
		arg.ReferralPercentagePctMode,
		arg.ReferralPercentageSbMode,
		arg.CountdownSeconds,
	)
	return err
}
