// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package repository

import (
	"context"
)

const getSiteSettings = `-- name: GetSiteSettings :one
SELECT id, rake_mode, rake_percentage, referral_percentage_pct_mode, referral_percentage_sb_mode, countdown_seconds,
       real_deposits_enabled, deposit_account_name, deposit_account_number, updated_at
FROM site_settings
WHERE id = 1 LIMIT 1
`

func (q *Queries) GetSiteSettings(ctx context.Context) (SiteSetting, error) {
	row := q.db.QueryRowContext(ctx, getSiteSettings)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.RakeMode,
		&i.RakePercentage,
		&i.ReferralPercentagePctMode,
		&i.ReferralPercentageSbMode,
		&i.CountdownSeconds,
		&i.RealDepositsEnabled,
		&i.DepositAccountName,
		&i.DepositAccountNumber,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSiteSettings = `-- name: UpdateSiteSettings :exec
UPDATE site_settings
SET rake_mode = $1,
    rake_percentage = $2,
    referral_percentage_pct_mode = $3,
    referral_percentage_sb_mode = $4,
    countdown_seconds = $5,
    real_deposits_enabled = $6,
    deposit_account_name = $7,
    deposit_account_number = $8,
    updated_at = NOW()
WHERE id = 1
`

type UpdateSiteSettingsParams struct {
	RakeMode                  string
	RakePercentage            float64
	ReferralPercentagePctMode float64
	ReferralPercentageSbMode  float64
	CountdownSeconds          int32
	RealDepositsEnabled       bool
	DepositAccountName        string
	DepositAccountNumber      string
}

// updated_at is set here rather than by the column: PostgreSQL has no
// ON UPDATE CURRENT_TIMESTAMP.
func (q *Queries) UpdateSiteSettings(ctx context.Context, arg UpdateSiteSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSiteSettings,
		arg.RakeMode,
		arg.RakePercentage,
		arg.ReferralPercentagePctMode,
		arg.ReferralPercentageSbMode,
		arg.CountdownSeconds,
		arg.RealDepositsEnabled,
		arg.DepositAccountName,
		arg.DepositAccountNumber,
	)
	return err
}
