// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package repository

import (
	"context"
	"database/sql"
)

const createTransaction = `-- name: CreateTransaction :execresult
INSERT INTO transactions (user_id, amount, reason, transaction_id)
VALUES (?, ?, ?, ?)
`

type CreateTransactionParams struct {
	UserID        int64
	Amount        string
	Reason        string
	TransactionID string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Reason,
		arg.TransactionID,
	)
}

const getTransactionsByUserID = `-- name: GetTransactionsByUserID :many
SELECT id, user_id, amount, reason, transaction_id, created_at
FROM transactions
WHERE user_id = ?
ORDER BY id DESC LIMIT 50
`

func (q *Queries) GetTransactionsByUserID(ctx context.Context, userID int64) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Reason,
			&i.TransactionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
