// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package repository

import (
	"context"
	"time"
)

const countTransactionsByUserID = `-- name: CountTransactionsByUserID :one
SELECT COUNT(*) AS total
FROM transactions
WHERE user_id = $1
`

func (q *Queries) CountTransactionsByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionsByUserID, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, amount, type, reason, transaction_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateTransactionParams struct {
	UserID        int64
	Amount        int64
	Type          string
	Reason        string
	TransactionID string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Type,
		arg.Reason,
		arg.TransactionID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const filterTransactions = `-- name: FilterTransactions :many
SELECT t.id, t.user_id, t.amount, t.type, t.reason, t.transaction_id, t.created_at, u.username
FROM transactions t
JOIN users u ON u.id = t.user_id
WHERE u.username ILIKE $1::text
  AND ($2::text = '' OR t.type = $2::text)
ORDER BY t.id DESC
LIMIT $4::int OFFSET $3::int
`

type FilterTransactionsParams struct {
	Username   string
	TypeFilter string
	RowOffset  int32
	RowLimit   int32
}

type FilterTransactionsRow struct {
	ID            int64
	UserID        int64
	Amount        int64
	Type          string
	Reason        string
	TransactionID string
	CreatedAt     time.Time
	Username      string
}

func (q *Queries) FilterTransactions(ctx context.Context, arg FilterTransactionsParams) ([]FilterTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, filterTransactions,
		arg.Username,
		arg.TypeFilter,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilterTransactionsRow
	for rows.Next() {
		var i FilterTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Type,
			&i.Reason,
			&i.TransactionID,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByUserID = `-- name: ListTransactionsByUserID :many
SELECT id, user_id, amount, type, reason, transaction_id, created_at
FROM transactions
WHERE user_id = $1
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByUserIDParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListTransactionsByUserID(ctx context.Context, arg ListTransactionsByUserIDParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Type,
			&i.Reason,
			&i.TransactionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumTransactionAmountByTypeSince = `-- name: SumTransactionAmountByTypeSince :one
SELECT COALESCE(SUM(amount), 0)::BIGINT AS total
FROM transactions
WHERE type = $1 AND created_at >= $2
`

type SumTransactionAmountByTypeSinceParams struct {
	Type      string
	CreatedAt time.Time
}

// The cast is load-bearing: SUM() over a bigint column is numeric in
// PostgreSQL, which arrives in Go as a byte slice rather than an integer.
func (q *Queries) SumTransactionAmountByTypeSince(ctx context.Context, arg SumTransactionAmountByTypeSinceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumTransactionAmountByTypeSince, arg.Type, arg.CreatedAt)
	var total int64
	err := row.Scan(&total)
	return total, err
}
