// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users WHERE role != 'house'
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, phone_number, password_hash, wallet, referral_code, referred_by, role)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateUserParams struct {
	Username     string
	PhoneNumber  string
	PasswordHash string
	Wallet       int64
	ReferralCode string
	ReferredBy   sql.NullString
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.PhoneNumber,
		arg.PasswordHash,
		arg.Wallet,
		arg.ReferralCode,
		arg.ReferredBy,
		arg.Role,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, phone_number, password_hash, wallet, referral_code, referred_by, role, created_at
FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Wallet,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, username, phone_number, password_hash, wallet, referral_code, referred_by, role, created_at
FROM users
WHERE phone_number = $1 LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Wallet,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByReferralCode = `-- name: GetUserByReferralCode :one
SELECT id, username, phone_number, password_hash, wallet, referral_code, referred_by, role, created_at
FROM users
WHERE referral_code = $1 LIMIT 1
`

func (q *Queries) GetUserByReferralCode(ctx context.Context, referralCode string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByReferralCode, referralCode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Wallet,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, phone_number, password_hash, wallet, referral_code, referred_by, role, created_at
FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Wallet,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, phone_number, password_hash, wallet, referral_code, referred_by, role, created_at
FROM users
WHERE role != 'house'
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PhoneNumber,
			&i.PasswordHash,
			&i.Wallet,
			&i.ReferralCode,
			&i.ReferredBy,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, phone_number, password_hash, wallet, referral_code, referred_by, role, created_at
FROM users
WHERE role != 'house' AND (username ILIKE $1 OR phone_number ILIKE $2)
ORDER BY id DESC
LIMIT $3 OFFSET $4
`

type SearchUsersParams struct {
	Username    string
	PhoneNumber string
	Limit       int32
	Offset      int32
}

// ILIKE, not LIKE: PostgreSQL's LIKE is case-sensitive, so an admin searching
// for "Alice" would miss the user "alice" entirely.
func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers,
		arg.Username,
		arg.PhoneNumber,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PhoneNumber,
			&i.PasswordHash,
			&i.Wallet,
			&i.ReferralCode,
			&i.ReferredBy,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           int64
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserPhone = `-- name: UpdateUserPhone :exec
UPDATE users
SET phone_number = $1
WHERE id = $2
`

type UpdateUserPhoneParams struct {
	PhoneNumber string
	ID          int64
}

func (q *Queries) UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPhone, arg.PhoneNumber, arg.ID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users
SET role = $1
WHERE id = $2
`

type UpdateUserRoleParams struct {
	Role string
	ID   int64
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.Role, arg.ID)
	return err
}

const updateUserWallet = `-- name: UpdateUserWallet :exec
UPDATE users
SET wallet = wallet + $1
WHERE id = $2
`

type UpdateUserWalletParams struct {
	Wallet int64
	ID     int64
}

func (q *Queries) UpdateUserWallet(ctx context.Context, arg UpdateUserWalletParams) error {
	_, err := q.db.ExecContext(ctx, updateUserWallet, arg.Wallet, arg.ID)
	return err
}
