// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (username, phone_number, password_hash, wallet, referral_code, referred_by)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	Username     string
	PhoneNumber  string
	PasswordHash string
	Wallet       string
	ReferralCode string
	ReferredBy   sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Username,
		arg.PhoneNumber,
		arg.PasswordHash,
		arg.Wallet,
		arg.ReferralCode,
		arg.ReferredBy,
	)
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, phone_number, password_hash, wallet, referral_code, referred_by, created_at
FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Wallet,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, username, phone_number, password_hash, wallet, referral_code, referred_by, created_at
FROM users
WHERE phone_number = ? LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Wallet,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByReferralCode = `-- name: GetUserByReferralCode :one
SELECT id, username, phone_number, password_hash, wallet, referral_code, referred_by, created_at
FROM users
WHERE referral_code = ? LIMIT 1
`

func (q *Queries) GetUserByReferralCode(ctx context.Context, referralCode string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByReferralCode, referralCode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Wallet,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, phone_number, password_hash, wallet, referral_code, referred_by, created_at
FROM users
WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Wallet,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserWallet = `-- name: UpdateUserWallet :exec
UPDATE users
SET wallet = wallet + ?
WHERE id = ?
`

type UpdateUserWalletParams struct {
	Wallet string
	ID     int64
}

func (q *Queries) UpdateUserWallet(ctx context.Context, arg UpdateUserWalletParams) error {
	_, err := q.db.ExecContext(ctx, updateUserWallet, arg.Wallet, arg.ID)
	return err
}
